### ISSUE TITLE
Paypal-Connector while passing map values

### ISSUE THREAD

**Issue by akshay1234** [mulesoft/paypal-connector#3]
[12:21:55] Nagarjuna N: WARN  2014-02-25 22:49:18,062 [[paypaltest].connector.http.mule.default.receiver.02] org.mule.transport.http.HttpMessageReceiver: No receiver found with secondary lookup on connector: connector.http.mule.default with URI key: http://localhost:8081/favicon.ico
WARN  2014-02-25 22:49:18,064 [[paypaltest].connector.http.mule.default.receiver.02] org.mule.transport.http.HttpMessageReceiver: Receivers on connector are: {
http://localhost:8081/paypal-demo-process-payment=HttpMessageReceiver{this=17359c0b, receiverKey=http://localhost:8081/paypal-demo-process-payment, endpoint=http://localhost:8081/paypal-demo-process-payment}
}
ERROR 2014-02-25 22:49:25,805 [[paypaltest].connector.http.mule.default.receiver.02] org.mule.exception.DefaultMessagingExceptionStrategy: 
********************************************************************************
Message               : Failed to invoke doDirectPayment. Message payload is of type: PaypalTestPayload
Code                  : MULE_ERROR--2
--------------------------------------------------------------------------------
Exception stack is:
1. Property key in class class ebay.apis.eblbasecomponents.CreditCardDetailsType is not readable (java.lang.IllegalArgumentException)
  net.sf.staccatocommons.check.Ensure$1:29 (null)
2. Failed to invoke doDirectPayment. Message payload is of type: PaypalTestPayload (org.mule.api.MessagingException)
  org.mule.module.paypal.processors.DoDirectPaymentMessageProcessor:451 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/api/MessagingException.html)
--------------------------------------------------------------------------------
Root Exception stack trace:
java.lang.IllegalArgumentException: Property key in class class ebay.apis.eblbasecomponents.CreditCardDetailsType is not readable
	at net.sf.staccatocommons.check.Ensure$1.createException(Ensure.java:29)
	at net.sf.staccatocommons.check.Ensure$1.createException(Ensure.java:1)
	at net.sf.staccatocommons.check.Check.fail(Check.java:98)
    + 3 more (set debug level logging or '-Dmule.verbose.exceptions=true' for everything)

and this is my flow
............................................................................................
 ```xml
<mule>
<flow>
<custom-transformer class="org.mule.transport.http.transformers.HttpRequestBodyToParamMap" name="Java" doc:name="Java"/>
    <custom-transformer class="com.crowdbucks.ParamMapToTestPayloadTransformer" name="Java1" doc:name="Java"/>
    <paypal:config name="Paypal" password="XXXXXXX" signature="XXXXXXX" username="XXXXXX" defaultCurrency="USD" doc:name="Paypal"/>
    <flow name="PaypalTestFlow1" doc:name="PaypalTestFlow1">
        <http:inbound-endpoint exchange-pattern="request-response" host="localhost" port="8081" doc:name="HTTP" path="paypal-demo-process-payment"/>
        <transformer ref="Java" doc:name="Transformer Reference"/>
        <transformer ref="Java1" doc:name="Transformer Reference"/>
        <paypal:do-direct-payment config-ref="Paypal"    doc:name="Paypal" ipAddress="127.0.0.1" paymentAction="AUTHORIZATION">
        	<paypal:card-details>
        			<paypal:card-detail key="key" value-ref="#[ognl:cardDetails]" />
        	</paypal:card-details>
        	<paypal:payment-details >
        			<paypal:payment-detail key="key" value-ref="#[ognl:paymentDetails]" />
        	</paypal:payment-details>
        </paypal:do-direct-payment>
        <paypal:capture config-ref="Paypal" amount="#[ognl:transactionID]" authorizationId="#[ognl:amount.value]" complete="true" doc:name="Paypal"/>
        <echo-component doc:name="Echo"/>
    </flow>
</mule>
 ```

**Comment by veigap** [comment]
Issue is solved in the new connector implementation.
