### ISSUE TITLE
"GetBalanceResponseType" is missing an @XmlRootElement annotation

### ISSUE THREAD

**Issue by ggdio** [mulesoft/paypal-connector#4]
The conector does not operate as expected. 
When calling any of paypal methods, JAXB cannot serialize/deserialize the response class. For example the following class for method getBalance: 
ebay.api.paypalapi.GetBalanceResponseType 

It throws:

1. unable to marshal type "ebay.api.paypalapi.GetBalanceResponseType" as an element because it is missing an @XmlRootElement annotation (com.sun.istack.SAXException2)
  com.sun.xml.bind.v2.runtime.XMLSerializer:244 (null)
2. null (javax.xml.bind.MarshalException)
  com.sun.xml.bind.v2.runtime.MarshallerImpl:328 (http://java.sun.com/j2ee/sdk_1.3/techdocs/api/javax/xml/bind/MarshalException.html)
3. failed to mashal objec tto XML (java.io.IOException)
  org.mule.module.xml.transformer.jaxb.JAXBMarshallerTransformer$1:110 (null)
4. failed to mashal objec tto XML (java.io.IOException). Message payload is of type: HttpResponse (org.mule.execution.ResponseDispatchException)
  org.mule.transport.http.HttpMessageProcessTemplate:141 (http://www.mulesoft.org/docs/site/current3/apidocs/org/mule/execution/ResponseDispatchException.html)

**Comment by veigap** [comment]
Issue will be solved in the new release.
